#! /usr/bin/env ruby


# insert code example:
# cb-rb -i <codeid> -f <filename,start> [-I <indent>]


require 'rhload';

$version = 'v1';
$toolhome = File.dirname(File.absolute_path(__FILE__));
$LOAD_PATH << $toolhome;
$lib = "lib_#{$version}";

rhload "#{$lib}/debugger.rb";
rhload "#{$lib}/exceptions.rb";
rhload "#{$lib}/options.rb";
rhload "#{$lib}/fileoperator.rb";
rhload "#{$lib}/database.rb";
rhload "#{$lib}/mainentry.rb";

debug=Debugger.new(false);
e = MainEntry.new(debug);
$SIG = e.run();
debug.print("program exists with sig: #{$SIG}");
exit $SIG;
